# Site settings
title: Zerbarian
email: flaver@zerbarian.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: flaver12
github_username:  flaver12

# Build settings
markdown: kramdown
#Enable this if you have the api running on 4000
#port: 5000
